"""empty message

Revision ID: 138ccd6ff566
Revises: 69f682394874
Create Date: 2020-08-13 08:10:24.166164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '138ccd6ff566'
down_revision = '69f682394874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('predictions_unique_semver', 'predictions', ['model_id', 'version'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('predictions_unique_semver', 'predictions', type_='unique')
    # ### end Alembic commands ###
