"""empty message

Revision ID: 1454c94dd5bb
Revises: 0e3cff90d380
Create Date: 2020-07-13 19:42:49.397212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1454c94dd5bb'
down_revision = '0e3cff90d380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('checkpoint_link', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('predictions', sa.Column('tfrecord_link', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ml_models', sa.Column('archived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'checkpoint_link')
    op.drop_column('predictions', 'tfrecord_link')
    op.drop_column('ml_models', 'archived')
    # ### end Alembic commands ###
