"""empty message

Revision ID: 25fbdbef2ced
Revises: 07fef677d603
Create Date: 2020-02-26 08:08:30.952898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fbdbef2ced'
down_revision = '07fef677d603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_models', sa.Column('project_url', sa.String(), nullable=True))
    op.drop_column('ml_models', 'dockerhub_url')
    op.drop_index('idx_prediction_tiles_centroid', table_name='prediction_tiles')
    op.add_column('predictions', sa.Column('docker_url', sa.String(), nullable=True))
    op.drop_index('idx_predictions_bbox', table_name='predictions')
    op.drop_column('predictions', 'dockerhub_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('dockerhub_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('idx_predictions_bbox', 'predictions', ['bbox'], unique=False)
    op.drop_column('predictions', 'docker_url')
    op.create_index('idx_prediction_tiles_centroid', 'prediction_tiles', ['centroid'], unique=False)
    op.add_column('ml_models', sa.Column('dockerhub_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ml_models', 'project_url')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
