"""empty message

Revision ID: 3d61fa79ba2d
Revises: 1670dcbf715d
Create Date: 2019-05-30 14:48:16.610231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d61fa79ba2d'
down_revision = '1670dcbf715d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], name='fk_models_versions'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('ml_models', 'dockerhub_hash')
    op.add_column('predictions', sa.Column('dockerhub_hash', sa.String(), nullable=True))
    op.add_column('predictions', sa.Column('version_id', sa.Integer(), nullable=False))
    op.create_foreign_key('ml_model_versions_fk', 'predictions', 'ml_model_versions', ['version_id'], ['id'])
    op.drop_column('predictions', 'version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('ml_model_versions_fk', 'predictions', type_='foreignkey')
    op.drop_column('predictions', 'version_id')
    op.drop_column('predictions', 'dockerhub_hash')
    op.add_column('ml_models', sa.Column('dockerhub_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('ml_model_versions')
    # ### end Alembic commands ###
