"""empty message

Revision ID: 3f891feff8ba
Revises: 65ed3558bb8e
Create Date: 2019-05-30 15:29:53.938781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f891feff8ba'
down_revision = '65ed3558bb8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_model_versions', sa.Column('version_major', sa.Integer(), nullable=False))
    op.add_column('ml_model_versions', sa.Column('version_minor', sa.Integer(), nullable=False))
    op.add_column('ml_model_versions', sa.Column('version_patch', sa.Integer(), nullable=False))
    op.drop_column('ml_model_versions', 'version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_model_versions', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('ml_model_versions', 'version_patch')
    op.drop_column('ml_model_versions', 'version_minor')
    op.drop_column('ml_model_versions', 'version_major')
    # ### end Alembic commands ###
