"""empty message

Revision ID: 4a6a607bbc8f
Revises: 0ad24de85333
Create Date: 2020-06-08 19:10:00.567729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a6a607bbc8f'
down_revision = '0ad24de85333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_tiles', sa.Column('validity', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction_tiles', 'validity')
    # ### end Alembic commands ###
