"""empty message

Revision ID: 5106403cbc29
Revises: 1454c94dd5bb
Create Date: 2020-07-14 14:10:46.423929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5106403cbc29'
down_revision = '1454c94dd5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
