"""empty message

Revision ID: 65b0dbc13dcb
Revises: 4a6a607bbc8f
Create Date: 2020-06-25 09:45:15.130267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b0dbc13dcb'
down_revision = '4a6a607bbc8f'
branch_labels = None
depends_on = None


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('inf_list', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('predictions', sa.Column('inf_type', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('predictions', sa.Column('inf_binary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'inf_type')
    op.drop_column('predictions', 'inf_list')
    op.drop_column('predictions', 'inf_binary')
    # ### end Alembic commands ###

