"""empty message

Revision ID: 65ed3558bb8e
Revises: 3d61fa79ba2d
Create Date: 2019-05-30 15:15:34.083946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ed3558bb8e'
down_revision = '3d61fa79ba2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_model_versions', sa.Column('version', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_model_versions', 'version')
    # ### end Alembic commands ###
