"""empty message

Revision ID: 7abacee99e4d
Revises: 138ccd6ff566
Create Date: 2020-08-17 11:23:08.362401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7abacee99e4d'
down_revision = '138ccd6ff566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration', sa.Column('auth', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration', 'auth')
    # ### end Alembic commands ###
