"""empty message

Revision ID: b08b77c1bb94
Revises: 29c35399c52d
Create Date: 2019-05-21 17:12:12.691355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b08b77c1bb94'
down_revision = '29c35399c52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_models', sa.Column('dockerhub_hash', sa.String(), nullable=True))
    op.drop_column('ml_models', 'dockethub_hash')
    op.drop_column('predictions', 'predictions')
    op.add_column('predictions', sa.Column('predictions', postgresql.JSONB(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_models', sa.Column('dockethub_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ml_models', 'dockerhub_hash')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
