"""empty message

Revision ID: c2cdb5688390
Revises: 5106403cbc29
Create Date: 2020-07-17 08:41:18.335778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2cdb5688390'
down_revision = '5106403cbc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('version', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('predictions', 'version_id')
    op.drop_column('predictions', 'bbox')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'version')
    op.add_column('predictions', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('predictions', sa.Column('bbox', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326), nullable=True))
    # ### end Alembic commands ###
