"""empty message

Revision ID: eda781be6e93
Revises: 25fbdbef2ced
Create Date: 2020-03-05 07:36:19.329546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda781be6e93'
down_revision = '25fbdbef2ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('docker_link', sa.String(), nullable=True))
    op.add_column('predictions', sa.Column('log_link', sa.String(), nullable=True))
    op.add_column('predictions', sa.Column('model_link', sa.String(), nullable=True))
    op.add_column('predictions', sa.Column('save_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'save_link')
    op.drop_column('predictions', 'model_link')
    op.drop_column('predictions', 'log_link')
    op.drop_column('predictions', 'docker_link')
    # ### end Alembic commands ###
