"""empty message

Revision ID: f4a2a808cf0a
Revises: c23d97930318
Create Date: 2019-05-20 17:46:02.329310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a2a808cf0a'
down_revision = 'c23d97930318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('predictions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], name='fk_models'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    # ### end Alembic commands ###
