"""empty message

Revision ID: f50003753b9f
Revises: 3f891feff8ba
Create Date: 2019-06-04 15:10:34.172430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50003753b9f'
down_revision = '3f891feff8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('tile_zoom', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'tile_zoom')
    # ### end Alembic commands ###
